### ISSUE TITLE
happy to contribute

### ISSUE THREAD

**Issue by nteetor** [mitchelloharawild/icon#1]
Hello again, I wanted to reiterate my willingness to help out as I know this is a utility I would use (and certainly others). If the project gets to the point where someone could lend a hand, please feel free to let me know.

**Comment by mitchelloharawild** [comment]
Sounds good, will keep this in mind. The infrastructure around the package is almost complete.
Once this is done (hopefully this month) there will be an opportunity to add lots of new icon libraries to the package. PRs for this will be encouraged (and I'll write a small vignette on how this can be done).

**Comment by mitchelloharawild** [comment]
After a bunch of discussions with R users (and since realising how many people use/need this package) I've returned to working on this package to get it on CRAN.

With [hacktoberfest](https://hacktoberfest.digitalocean.com/) just around the corner, I'm planning to put up several issues (from easy-medium difficulty) giving people the opportunity to contribute. Many of these issues will involve adding icon support for a bunch of icon libraries that I can find around the web.

So if you're still interested in contributing, keep an eye on the issues throughout October.

**Comment by mitchelloharawild** [comment]
Closing due to repo merge. If you're still interested in contributing, you can look at how other icon libraries have been set up, or wait for an icon extensions development vignette.
