### ISSUE TITLE
Bummed out by breaking changes

### ISSUE THREAD

**Issue by friendly** [mitchelloharawild/icon#66]
<gripe>
Just upgraded to R 4.1.2, and discovered that I can no longer use the `icon` package in my Rmd files. Nor can I install it because
somehow `remotes::install_github("ropenscilabs/icon")` vectors to your new `icons` package, and I can't find the `icon` source package to install it for R 4+.

This is a disaster for me because the syntax for `icons` is so different, e.g., `icon::fa("rocket", color="red")` vs.
`icons::icon_style(fontawesome("rocket"), fill="red")`

This is probably the **worst example** of breaking changes I have ever seen.
It means I will either have to revert to R 3.6 or else modify all the Rmd files for my web sites that use `r icon::fa()`

You could have provided some cover functions to make the transition easier.
</gripe>

**Comment by mitchelloharawild** [comment]
You can install the 'icon' package v0.1.0 with `remotes::install_github("mitchelloharawild/icons@v0.1.0")`. This should allow your old work to continue to run.

Some substantial breaking changes weren't avoidable (such as changing the package name), and so with the migration from ropenscilabs and a complete rewrite of the package to use SVG instead of fonts, I made some design changes to improve the extensibility design of the package.

**Comment by friendly** [comment]
Design changes to improve extensibility should be made with some consideration of backward compatibility.

Also, you should publicize the availability of the old version.

**Comment by mitchelloharawild** [comment]
Apologies again for the breaking changes, I've added these install instructions to the README section noting the breaking changes.
